"""
algorithms/pdf_export.py

Generates polished PDF reports for any of the three report types
(plagiarism, compression, duplicate) using reportlab.

This is a pure utility module with no PyQt dependency, so it can be
unit-tested independently of the GUI.
"""

import os
from datetime import datetime
from typing import Dict

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak,
)

from models.report import (
    Report, REPORT_TYPE_PLAGIARISM, REPORT_TYPE_COMPRESSION, REPORT_TYPE_DUPLICATE,
)


def _build_styles():
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(
        name="ReportTitle", fontSize=20, leading=24, spaceAfter=6,
        textColor=colors.HexColor("#2E3A87"), fontName="Helvetica-Bold",
    ))
    styles.add(ParagraphStyle(
        name="ReportSubtitle", fontSize=10, leading=14,
        textColor=colors.HexColor("#666666"), spaceAfter=14,
    ))
    styles.add(ParagraphStyle(
        name="SectionHeading", fontSize=13, leading=16, spaceBefore=14, spaceAfter=8,
        textColor=colors.HexColor("#2E3A87"), fontName="Helvetica-Bold",
    ))
    styles.add(ParagraphStyle(
        name="BodyTextSmall", fontSize=9.5, leading=13,
    ))
    return styles


def _section_table(rows, col_widths=(7 * cm, 7 * cm)):
    table = Table(rows, colWidths=list(col_widths))
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#F0F2FA")),
        ("TEXTCOLOR", (0, 0), (-1, -1), colors.HexColor("#222222")),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (1, 0), (1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 9.5),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CCCCCC")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    return table


def _wrap_word_list(words, max_words=60) -> str:
    if not words:
        return "None"
    shown = words[:max_words]
    text = ", ".join(shown)
    if len(words) > max_words:
        text += f"  ... (+{len(words) - max_words} more)"
    return text


def export_plagiarism_report(report: Report, output_path: str) -> str:
    """Render a plagiarism Report as a PDF document at output_path."""
    data = report.data
    styles = _build_styles()
    doc = SimpleDocTemplate(
        output_path, pagesize=A4,
        leftMargin=2 * cm, rightMargin=2 * cm, topMargin=2 * cm, bottomMargin=2 * cm,
    )
    flow = []

    flow.append(Paragraph("Plagiarism Detection Report", styles["ReportTitle"]))
    flow.append(Paragraph(
        f"Generated by Smart Academic Integrity &amp; File Optimization Suite &nbsp;|&nbsp; "
        f"{report.display_date()}", styles["ReportSubtitle"],
    ))

    flow.append(Paragraph("Comparison Overview", styles["SectionHeading"]))
    overview_rows = [
        ["Document A", data.get("label_a", "Text A")],
        ["Document B", data.get("label_b", "Text B")],
        ["Overall Similarity", f"{data.get('overall_similarity_percent', 0)}%"],
        ["Jaccard Similarity", f"{data.get('jaccard_score', 0)}%"],
        ["Cosine Similarity", f"{data.get('cosine_score', 0)}%"],
        ["Matching Word Count", str(data.get("matching_word_count", 0))],
        ["Word Count (A)", str(data.get("word_count_a", 0))],
        ["Word Count (B)", str(data.get("word_count_b", 0))],
        ["Time Taken", f"{data.get('time_taken_seconds', 0)} seconds"],
    ]
    flow.append(_section_table(overview_rows))

    flow.append(Paragraph("Common Keywords", styles["SectionHeading"]))
    flow.append(Paragraph(_wrap_word_list(data.get("common_words", [])), styles["BodyTextSmall"]))

    flow.append(Paragraph("Unique to Document A", styles["SectionHeading"]))
    flow.append(Paragraph(_wrap_word_list(data.get("unique_to_a", [])), styles["BodyTextSmall"]))

    flow.append(Paragraph("Unique to Document B", styles["SectionHeading"]))
    flow.append(Paragraph(_wrap_word_list(data.get("unique_to_b", [])), styles["BodyTextSmall"]))

    matching_phrases = data.get("matching_phrases", [])
    flow.append(Paragraph("Matching Phrases Detected", styles["SectionHeading"]))
    if matching_phrases:
        for phrase in matching_phrases[:40]:
            flow.append(Paragraph(f"&bull; {phrase}", styles["BodyTextSmall"]))
    else:
        flow.append(Paragraph("No contiguous matching phrases detected.", styles["BodyTextSmall"]))

    doc.build(flow)
    return output_path


def export_compression_report(report: Report, output_path: str) -> str:
    """Render a compression Report as a PDF document at output_path."""
    data = report.data
    styles = _build_styles()
    doc = SimpleDocTemplate(
        output_path, pagesize=A4,
        leftMargin=2 * cm, rightMargin=2 * cm, topMargin=2 * cm, bottomMargin=2 * cm,
    )
    flow = []

    flow.append(Paragraph("File Compression Report", styles["ReportTitle"]))
    flow.append(Paragraph(
        f"Generated by Smart Academic Integrity &amp; File Optimization Suite &nbsp;|&nbsp; "
        f"{report.display_date()}", styles["ReportSubtitle"],
    ))

    flow.append(Paragraph("Compression Summary", styles["SectionHeading"]))
    rows = [
        ["File", data.get("filename", "-")],
        ["Original Size", f"{data.get('original_size', 0):,} bytes"],
        ["Compressed Size", f"{data.get('compressed_size', 0):,} bytes"],
        ["Compression Ratio", str(data.get("compression_ratio", "-"))],
        ["Space Saved", f"{data.get('space_saved_percent', 0)}%"],
        ["Distinct Symbols", str(data.get("distinct_symbols", "-"))],
    ]
    flow.append(_section_table(rows))

    code_table = data.get("code_table_preview", [])
    if code_table:
        flow.append(Paragraph("Huffman Code Table (sample)", styles["SectionHeading"]))
        table_rows = [["Byte (char)", "Frequency", "Code"]] + code_table[:25]
        t = Table(table_rows, colWidths=[4 * cm, 4 * cm, 6 * cm])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2E3A87")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CCCCCC")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F7F8FC")]),
        ]))
        flow.append(t)

    doc.build(flow)
    return output_path


def export_duplicate_report(report: Report, output_path: str) -> str:
    """Render a duplicate-scan Report as a PDF document at output_path."""
    data = report.data
    styles = _build_styles()
    doc = SimpleDocTemplate(
        output_path, pagesize=A4,
        leftMargin=2 * cm, rightMargin=2 * cm, topMargin=2 * cm, bottomMargin=2 * cm,
    )
    flow = []

    flow.append(Paragraph("Duplicate File Scan Report", styles["ReportTitle"]))
    flow.append(Paragraph(
        f"Generated by Smart Academic Integrity &amp; File Optimization Suite &nbsp;|&nbsp; "
        f"{report.display_date()}", styles["ReportSubtitle"],
    ))

    flow.append(Paragraph("Scan Summary", styles["SectionHeading"]))
    rows = [
        ["Scanned Directory", data.get("root_dir", "-")],
        ["Total Files Scanned", str(data.get("total_files_scanned", 0))],
        ["Duplicate Groups", str(data.get("duplicate_groups_count", 0))],
        ["Duplicate Files", str(data.get("duplicate_files_count", 0))],
        ["Wasted Storage", data.get("wasted_human", "0 B")],
    ]
    flow.append(_section_table(rows))

    groups = data.get("groups_preview", [])
    if groups:
        flow.append(Paragraph("Duplicate Groups", styles["SectionHeading"]))
        for i, group in enumerate(groups[:20], start=1):
            flow.append(Paragraph(f"Group {i} ({len(group)} files):", styles["BodyTextSmall"]))
            for path in group:
                flow.append(Paragraph(f"&nbsp;&nbsp;&bull; {path}", styles["BodyTextSmall"]))

    doc.build(flow)
    return output_path


def export_report(report: Report, output_path: str) -> str:
    """Dispatch to the correct exporter based on report.report_type."""
    if report.report_type == REPORT_TYPE_PLAGIARISM:
        return export_plagiarism_report(report, output_path)
    elif report.report_type == REPORT_TYPE_COMPRESSION:
        return export_compression_report(report, output_path)
    elif report.report_type == REPORT_TYPE_DUPLICATE:
        return export_duplicate_report(report, output_path)
    else:
        raise ValueError(f"Unknown report type: {report.report_type}")
